export type Vendor = { id:string; name:string; email:string; wallet:string; budget:string; color:string };
export type Invoice = { id:string; vendorId:string; reference:string; description:string; amount:string; recipient:string; due:string; revision:number; status:'review'|'approved'|'paid'; approval?:{digest:string; signature?:string; signer?:string; at:string}; receipt?:string; source?:string };
export type Audit = { id:string; at:string; action:string; detail:string; previousHash:string; hash:string };
export type State = { vendors:Vendor[]; invoices:Invoice[]; audit:Audit[]; mode:'demo'|'testnet'; network:{chainId:number; contract:string; token:string}; };
export const addressPattern = /^0x[0-9a-fA-F]{40}$/;
export function units(amount:string):bigint { if(!/^\d{1,12}(\.\d{1,6})?$/.test(amount)) throw new Error('Enter a positive amount with at most six decimal places.'); const [a,b='']=amount.split('.'); const n=BigInt(a)*BigInt(1000000)+BigInt(b.padEnd(6,'0')); if(n<=BigInt(0))throw new Error('Amount must be positive.'); return n; }
export function checks(s:State,i:Invoice) { const v=s.vendors.find(v=>v.id===i.vendorId); const duplicate=s.invoices.some(x=>x.id!==i.id&&x.vendorId===i.vendorId&&x.reference.trim().toLowerCase()===i.reference.trim().toLowerCase()); let valid=true,over=false; try {const n=units(i.amount);over=!!v&&n>units(v.budget);}catch{valid=false;}
return [{name:'Registered recipient',ok:!!v&&i.recipient.toLowerCase()===v.wallet.toLowerCase(),detail:'The invoice wallet must match the vendor’s registered wallet.'},{name:'Unique invoice',ok:!duplicate,detail:'Same vendor and invoice reference cannot be submitted twice.'},{name:'Payment limit',ok:valid&&!over,detail:'Amount must fit the vendor’s per-payment limit.'},{name:'Valid destination',ok:addressPattern.test(i.recipient)&&!/^0x0{40}$/i.test(i.recipient),detail:'A non-zero EVM wallet address is required.'}]; }
export function payload(s:State,i:Invoice) { return JSON.stringify({invoiceId:i.id,vendorId:i.vendorId,reference:i.reference,amount:units(i.amount).toString(),recipient:i.recipient.toLowerCase(),revision:i.revision,chainId:s.network.chainId,contract:s.network.contract.toLowerCase(),token:s.network.token.toLowerCase(),mode:s.mode}); }
export async function hash(text:string) {const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,'0')).join('');}
export async function digest(s:State,i:Invoice){return hash(payload(s,i));}
export async function log(s:State,action:string,detail:string){const entry={id:crypto.randomUUID(),at:new Date().toISOString(),action,detail,previousHash:s.audit.at(-1)?.hash??'GENESIS'};s.audit.push({...entry,hash:await hash(JSON.stringify(entry))});}
export function seed():State {return {mode:'demo',network:{chainId:31337,contract:'',token:''},vendors:[{id:'v1',name:'Studio North',email:'billing@studionorth.example',wallet:'0x1111111111111111111111111111111111111111',budget:'5000',color:'#b8f56a'},{id:'v2',name:'Orbit Engineering',email:'finance@orbit.example',wallet:'0x2222222222222222222222222222222222222222',budget:'10000',color:'#96b7ff'},{id:'v3',name:'Mono Research',email:'hello@mono.example',wallet:'0x3333333333333333333333333333333333333333',budget:'2500',color:'#ddbbff'}],invoices:[{id:'demo-001',vendorId:'v1',reference:'SN-1042',description:'Brand system · final delivery',amount:'2400',recipient:'0x9999999999999999999999999999999999999999',due:'2026-10-14',revision:1,status:'review'},{id:'demo-002',vendorId:'v2',reference:'ORB-208',description:'API integration · October sprint',amount:'4800',recipient:'0x2222222222222222222222222222222222222222',due:'2026-10-16',revision:1,status:'review'},{id:'demo-003',vendorId:'v3',reference:'MR-091',description:'Customer discovery interviews',amount:'1250',recipient:'0x3333333333333333333333333333333333333333',due:'2026-10-18',revision:1,status:'review'}],audit:[]};}
