import {getChatGPTUser} from '@/app/chatgpt-auth';
import {read,write} from '@/lib/store';
import {seed,units,checks,digest,log,addressPattern,type Invoice} from '@/lib/model';
import {verifyMessage} from 'ethers';
export async function GET(){try{const u=await getChatGPTUser();if(!u)return Response.json({error:'Sign in to load your workspace.'},{status:401});return Response.json(await read(u.userId));}catch{ return Response.json({error:'Workspace unavailable. Please retry.'},{status:503});}}
export async function POST(req:Request){try{
const u=await getChatGPTUser();if(!u)return Response.json({error:'Sign in required.'},{status:401});
const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return Response.json({error:'Origin rejected'},{status:403});
const raw=await req.text();if(raw.length>100000)return Response.json({error:'Request too large'},{status:413});const b=JSON.parse(raw);let {state:s,version}=await read(u.userId);if(b.version!==version)throw new Error('Workspace changed. Refresh and retry.');
const i=s.invoices.find(i=>i.id===b.id);const str=(v:unknown,max=200)=>{if(typeof v!=='string'||!v.trim()||v.length>max)throw new Error('A required field is missing or too long.');return v.trim();};
if(b.action==='createInvoice') {const p=b.invoice;const v=s.vendors.find(v=>v.id===p.vendorId);if(!v)throw new Error('Select a vendor.');units(p.amount);if(!addressPattern.test(p.recipient))throw new Error('Invalid wallet.');if(!/^\d{4}-\d{2}-\d{2}$/.test(p.due))throw new Error('Invalid due date.');const item:Invoice={id:crypto.randomUUID(),vendorId:v.id,reference:str(p.reference,80),description:str(p.description,500),amount:p.amount,recipient:p.recipient,due:p.due,revision:1,status:'review',source:typeof p.source==='string'?p.source.slice(0,4000):undefined};if(s.invoices.length>=500)throw new Error('Prototype limit: 500 invoices.');s.invoices.unshift(item);await log(s,'Invoice created',`${item.reference} · ${item.amount} USDC`);}
else if(b.action==='createVendor'){if(s.vendors.length>=100)throw new Error('Prototype limit: 100 vendors.');const p=b.vendor;units(p.budget);if(!addressPattern.test(p.wallet)||/^0x0{40}$/i.test(p.wallet))throw new Error('Invalid vendor wallet.');s.vendors.push({id:crypto.randomUUID(),name:str(p.name,80),email:str(p.email,150),wallet:p.wallet,budget:p.budget,color:'#b8f56a'});await log(s,'Vendor registered',p.name);}
else if(b.action==='restoreRecipient'||b.action==='editInvoice'){if(!i||i.status==='paid')throw new Error('Invoice cannot be edited.');if(b.action==='restoreRecipient')i.recipient=s.vendors.find(v=>v.id===i.vendorId)!.wallet;else {units(b.amount);if(!addressPattern.test(b.recipient))throw new Error('Invalid wallet.');i.amount=b.amount;i.recipient=b.recipient;}i.revision++;i.status='review';delete i.approval;await log(s,'Approval invalidated',`${i.reference} details changed · revision ${i.revision}`);}
else if(b.action==='approve'){if(!i||i.status!=='review')throw new Error('Invoice is not awaiting review.');if(checks(s,i).some(c=>!c.ok))throw new Error('Resolve all payment checks first.');const d=await digest(s,i);i.approval={digest:d,at:new Date().toISOString()};i.status='approved';await log(s,'Demo approval recorded',`${i.reference} · ${d.slice(0,16)} · no wallet signature`);}
else if(b.action==='simulate'){if(!i||i.status!=='approved'||!i.approval)throw new Error('Approval required.');if(await digest(s,i)!==i.approval.digest||checks(s,i).some(c=>!c.ok))throw new Error('Payment details changed. Re-approval required.');i.status='paid';i.receipt='SIM-'+crypto.randomUUID();await log(s,'Payment simulated',`${i.reference} · no money moved · ${i.receipt}`);}
else if(b.action==='changeVendorWallet'){const v=s.vendors.find(v=>v.id===b.vendorId);if(!v||!addressPattern.test(b.newWallet)||/^0x0{40}$/i.test(b.newWallet))throw new Error('Invalid vendor or wallet.');const message=`PayFence wallet change\nWorkspace: ${u.userId}\nVendor: ${v.id}\nFrom: ${v.wallet.toLowerCase()}\nTo: ${b.newWallet.toLowerCase()}\nVersion: ${version}`;if(verifyMessage(message,b.signature).toLowerCase()!==v.wallet.toLowerCase())throw new Error('Signature must come from the currently registered vendor wallet.');v.wallet=b.newWallet;for(const x of s.invoices.filter(x=>x.vendorId===v.id&&x.status!=='paid')){x.status='review';delete x.approval;x.revision++;}await log(s,'Vendor wallet changed',`${v.name} · old-wallet signature verified`);}
else if(b.action==='walletMessage'){const v=s.vendors.find(v=>v.id===b.vendorId);if(!v)throw new Error('Vendor missing');return Response.json({message:`PayFence wallet change\nWorkspace: ${u.userId}\nVendor: ${v.id}\nFrom: ${v.wallet.toLowerCase()}\nTo: ${String(b.newWallet).toLowerCase()}\nVersion: ${version}`});}
else if(b.action==='reset'){s=seed();await log(s,'Demo reset','Sample workspace restored.');}
else throw new Error('Unknown action');
await write(u.userId,version,s);return Response.json({state:s,version:version+1});
}catch(e){return Response.json({error:e instanceof Error?e.message:'Operation failed.'},{status:400});}}
